import { Archivo } from "next/font/google";
import "./globals.css";
import ProviderWrapper from "./ProviderWrapper";

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${archivo.variable} antialiased`} style={{ fontFamily: 'var(--font-archivo), sans-serif' }}>
        <ProviderWrapper>{children}</ProviderWrapper>
      </body>
    </html>
  );
}
