import { Arimo } from "next/font/google";
import "./globals.css";
import ProviderWrapper from "./ProviderWrapper";

const arimo = Arimo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-arimo",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${arimo.variable} antialiased`} style={{ fontFamily: 'var(--font-arimo), sans-serif' }}>
        <ProviderWrapper>{children}</ProviderWrapper>
      </body>
    </html>
  );
}
